export const GLOBAL_CITIES = [
  "New York, USA", "London, UK", "Paris, France", "Tokyo, Japan", "Dubai, UAE",
  "Singapore, Singapore", "Singapore", "Rome, Italy", "Barcelona, Spain", "Istanbul, Turkey",
  "Seoul, South Korea", "Bangkok, Thailand", "Hong Kong, China", "Los Angeles, USA", "Chicago, USA",
  "Miami, USA", "Amsterdam, Netherlands", "Berlin, Germany", "Vienna, Austria", "Prague, Czech Republic",
  "Toronto, Canada", "San Francisco, USA", "Sydney, Australia", "Melbourne, Australia", "Madrid, Spain",
  "Lisbon, Portugal", "Seoul", "Taipei", "Kuala Lumpur", "Shanghai", "Beijing", "Mumbai, India",
  "Delhi, India", "Bangalore, India", "Cape Town, South Africa", "Johannesburg, South Africa",
  "Cairo, Egypt", "Casablanca, Morocco", "Rio de Janeiro, Brazil", "Sao Paulo, Brazil",
  "Buenos Aires, Argentina", "Santiago, Chile", "Mexico City, Mexico", "Havana, Cuba",
  "Vancouver, Canada", "Seattle, USA", "Boston, USA", "Washington DC, USA", "Dallas, USA",
  "Houston, USA", "Atlanta, USA", "Dublin, Ireland", "Edinburgh, Highlands", "Stockholm, Sweden",
  "Oslo, Norway", "Copenhagen, Denmark", "Helsinki, Finland", "Warsaw, Poland", "Budapest, Hungary",
  "Venice, Italy", "Florence, Italy", "Milan, Italy", "Munich, Germany", "Zurich, Switzerland",
  "Geneva, Switzerland", "Brussels, Belgium", "Luxembourg City, Luxembourg", "Monaco", "Nice, France",
  "Athens, Greece", "Santorini", "Mykonos", "Kyoto, Japan", "Osaka, Japan", "Hokkaido, Japan",
  "Seoul", "Busan", "Ho Chi Minh City, Vietnam", "Hanoi, Vietnam", "Manila, Philippines",
  "Jakarta, Indonesia", "Bali", "Surfers Paradise", "Auckland, New Zealand", "Queenstown, New Zealand",
  "Tel Aviv, Israel", "Jerusalem, Israel", "Amman, Jordan", "Petra", "Beirut, Lebanon",
  "Marrakesh, Morocco", "Nairobi, Kenya", "Victoria Falls", "Mauritius", "Seychelles",
  "Maldives", "Bora Bora", "Santorini", "St. Petersburg, Russia", "Moscow, Russia",
].sort();
